[build]
  functions = "functions"
  publish = "deploy"
[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"
[[redirects]]
  from = "/og/*"
  to = "/.netlify/builders/og"
  status = 200
  force = true